### ISSUE TITLE
Error while running sample

### ISSUE THREAD

**Issue by robots4every1** [kuka-isir/cart_opt_ctrl#2]
Hi,

I'm trying to run the sample code after following the install on read the docs and I get the following error:

Waiting for joint_trajectory_controller/follow_joint_trajectory to come up
[ERROR] [1423650038.665622513]: MoveitSimpleControllerManager: Action client not connected: /follow_joint_trajectory

Do you have any tips on what might be wrong?

**Comment by JimmyDaSilva** [comment]
Hi @robots4every1,
I am pretty sure it's just because you're not starting it.
To do so,  just change `YOUR_ROBOT_NAME_moveit_config/config/controllers.yaml` and just replace the name to `cart_opt_controller`.

For me the files looks like this:
```
controller_list:
  - name: cart_opt_controller    #previously joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_0,joint_1,joint_2,joint_3,joint_4,joint_5,joint_6]

```

Tell me if it works. I quite surprise to see you are using our package, and glad!
It's experimental though so be careful.
